//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.New
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Организация.
    /// </summary>
    // *** Start programmer edit section *** (Организация CustomAttributes)

    // *** End programmer edit section *** (Организация CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОрганизацияE", new string[] {
            "IDорганизации as \'I dорганизации\'",
            "Наименование as \'Наименование\'",
            "Адрес as \'Адрес\'",
            "ИНН as \'ИНН\'",
            "КПП as \'КПП\'",
            "ОГРН as \'ОГРН\'"})]
    [View("ОрганизацияL", new string[] {
            "IDорганизации as \'I dорганизации\'",
            "Наименование as \'Наименование\'",
            "Адрес as \'Адрес\'",
            "ИНН as \'ИНН\'",
            "КПП as \'КПП\'",
            "ОГРН as \'ОГРН\'"})]
    public class Организация : ICSSoft.STORMNET.DataObject
    {
        
        private int fIDорганизации;
        
        private string fНаименование;
        
        private string fАдрес;
        
        private int fИНН;
        
        private int fКПП;
        
        private int fОГРН;
        
        // *** Start programmer edit section *** (Организация CustomMembers)

        // *** End programmer edit section *** (Организация CustomMembers)

        
        /// <summary>
        /// IDорганизации.
        /// </summary>
        // *** Start programmer edit section *** (Организация.IDорганизации CustomAttributes)

        // *** End programmer edit section *** (Организация.IDорганизации CustomAttributes)
        public virtual int IDорганизации
        {
            get
            {
                // *** Start programmer edit section *** (Организация.IDорганизации Get start)

                // *** End programmer edit section *** (Организация.IDорганизации Get start)
                int result = this.fIDорганизации;
                // *** Start programmer edit section *** (Организация.IDорганизации Get end)

                // *** End programmer edit section *** (Организация.IDорганизации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.IDорганизации Set start)

                // *** End programmer edit section *** (Организация.IDорганизации Set start)
                this.fIDорганизации = value;
                // *** Start programmer edit section *** (Организация.IDорганизации Set end)

                // *** End programmer edit section *** (Организация.IDорганизации Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Организация.Адрес CustomAttributes)

        // *** End programmer edit section *** (Организация.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Организация.Адрес Get start)

                // *** End programmer edit section *** (Организация.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Организация.Адрес Get end)

                // *** End programmer edit section *** (Организация.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.Адрес Set start)

                // *** End programmer edit section *** (Организация.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Организация.Адрес Set end)

                // *** End programmer edit section *** (Организация.Адрес Set end)
            }
        }
        
        /// <summary>
        /// ИНН.
        /// </summary>
        // *** Start programmer edit section *** (Организация.ИНН CustomAttributes)

        // *** End programmer edit section *** (Организация.ИНН CustomAttributes)
        public virtual int ИНН
        {
            get
            {
                // *** Start programmer edit section *** (Организация.ИНН Get start)

                // *** End programmer edit section *** (Организация.ИНН Get start)
                int result = this.fИНН;
                // *** Start programmer edit section *** (Организация.ИНН Get end)

                // *** End programmer edit section *** (Организация.ИНН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.ИНН Set start)

                // *** End programmer edit section *** (Организация.ИНН Set start)
                this.fИНН = value;
                // *** Start programmer edit section *** (Организация.ИНН Set end)

                // *** End programmer edit section *** (Организация.ИНН Set end)
            }
        }
        
        /// <summary>
        /// КПП.
        /// </summary>
        // *** Start programmer edit section *** (Организация.КПП CustomAttributes)

        // *** End programmer edit section *** (Организация.КПП CustomAttributes)
        public virtual int КПП
        {
            get
            {
                // *** Start programmer edit section *** (Организация.КПП Get start)

                // *** End programmer edit section *** (Организация.КПП Get start)
                int result = this.fКПП;
                // *** Start programmer edit section *** (Организация.КПП Get end)

                // *** End programmer edit section *** (Организация.КПП Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.КПП Set start)

                // *** End programmer edit section *** (Организация.КПП Set start)
                this.fКПП = value;
                // *** Start programmer edit section *** (Организация.КПП Set end)

                // *** End programmer edit section *** (Организация.КПП Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Организация.Наименование CustomAttributes)

        // *** End programmer edit section *** (Организация.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Организация.Наименование Get start)

                // *** End programmer edit section *** (Организация.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Организация.Наименование Get end)

                // *** End programmer edit section *** (Организация.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.Наименование Set start)

                // *** End programmer edit section *** (Организация.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Организация.Наименование Set end)

                // *** End programmer edit section *** (Организация.Наименование Set end)
            }
        }
        
        /// <summary>
        /// ОГРН.
        /// </summary>
        // *** Start programmer edit section *** (Организация.ОГРН CustomAttributes)

        // *** End programmer edit section *** (Организация.ОГРН CustomAttributes)
        public virtual int ОГРН
        {
            get
            {
                // *** Start programmer edit section *** (Организация.ОГРН Get start)

                // *** End programmer edit section *** (Организация.ОГРН Get start)
                int result = this.fОГРН;
                // *** Start programmer edit section *** (Организация.ОГРН Get end)

                // *** End programmer edit section *** (Организация.ОГРН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.ОГРН Set start)

                // *** End programmer edit section *** (Организация.ОГРН Set start)
                this.fОГРН = value;
                // *** Start programmer edit section *** (Организация.ОГРН Set end)

                // *** End programmer edit section *** (Организация.ОГРН Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОрганизацияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизацияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизацияE", typeof(IIS.New.Организация));
                }
            }
            
            /// <summary>
            /// "ОрганизацияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизацияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизацияL", typeof(IIS.New.Организация));
                }
            }
        }
    }
}
