//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.New
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудник.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудник CustomAttributes)

    // *** End programmer edit section *** (Сотрудник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникE", new string[] {
            "IDдолжности as \'Idдолжности\'",
            "IDсотрудника as \'IDсотрудника\'",
            "IDПодразделения as \'Id подразделения\'",
            "ФИО as \'ФИО\'",
            "ИНН as \'ИНН\'",
            "Снилс as \'Снилс\'",
            "Номер_телефона as \'Номер_телефона\'"})]
    [View("СотрудникL", new string[] {
            "IDсотрудника as \'IDсотрудника\'",
            "IDдолжности as \'Idдолжности\'",
            "IDПодразделения as \'Id подразделения\'",
            "ФИО as \'ФИО\'",
            "ИНН as \'ИНН\'",
            "Снилс as \'Снилс\'",
            "Номер_телефона as \'Номер_телефона\'"})]
    public class Сотрудник : ICSSoft.STORMNET.DataObject
    {
        
        private int fIDдолжности;
        
        private int fIDсотрудника;
        
        private int fIDПодразделения;
        
        private string fФИО;
        
        private int fИНН;
        
        private int fСнилс;
        
        private int fНомер_телефона;
        
        private IIS.New.Должности fДолжности;
        
        private IIS.New.Подразделения fПодразделения;
        
        // *** Start programmer edit section *** (Сотрудник CustomMembers)

        // *** End programmer edit section *** (Сотрудник CustomMembers)

        
        /// <summary>
        /// IDдолжности.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.IDдолжности CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.IDдолжности CustomAttributes)
        public virtual int IDдолжности
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.IDдолжности Get start)

                // *** End programmer edit section *** (Сотрудник.IDдолжности Get start)
                int result = this.fIDдолжности;
                // *** Start programmer edit section *** (Сотрудник.IDдолжности Get end)

                // *** End programmer edit section *** (Сотрудник.IDдолжности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.IDдолжности Set start)

                // *** End programmer edit section *** (Сотрудник.IDдолжности Set start)
                this.fIDдолжности = value;
                // *** Start programmer edit section *** (Сотрудник.IDдолжности Set end)

                // *** End programmer edit section *** (Сотрудник.IDдолжности Set end)
            }
        }
        
        /// <summary>
        /// IDПодразделения.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.IDПодразделения CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.IDПодразделения CustomAttributes)
        public virtual int IDПодразделения
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.IDПодразделения Get start)

                // *** End programmer edit section *** (Сотрудник.IDПодразделения Get start)
                int result = this.fIDПодразделения;
                // *** Start programmer edit section *** (Сотрудник.IDПодразделения Get end)

                // *** End programmer edit section *** (Сотрудник.IDПодразделения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.IDПодразделения Set start)

                // *** End programmer edit section *** (Сотрудник.IDПодразделения Set start)
                this.fIDПодразделения = value;
                // *** Start programmer edit section *** (Сотрудник.IDПодразделения Set end)

                // *** End programmer edit section *** (Сотрудник.IDПодразделения Set end)
            }
        }
        
        /// <summary>
        /// IDсотрудника.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.IDсотрудника CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.IDсотрудника CustomAttributes)
        public virtual int IDсотрудника
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.IDсотрудника Get start)

                // *** End programmer edit section *** (Сотрудник.IDсотрудника Get start)
                int result = this.fIDсотрудника;
                // *** Start programmer edit section *** (Сотрудник.IDсотрудника Get end)

                // *** End programmer edit section *** (Сотрудник.IDсотрудника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.IDсотрудника Set start)

                // *** End programmer edit section *** (Сотрудник.IDсотрудника Set start)
                this.fIDсотрудника = value;
                // *** Start programmer edit section *** (Сотрудник.IDсотрудника Set end)

                // *** End programmer edit section *** (Сотрудник.IDсотрудника Set end)
            }
        }
        
        /// <summary>
        /// ИНН.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.ИНН CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.ИНН CustomAttributes)
        public virtual int ИНН
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.ИНН Get start)

                // *** End programmer edit section *** (Сотрудник.ИНН Get start)
                int result = this.fИНН;
                // *** Start programmer edit section *** (Сотрудник.ИНН Get end)

                // *** End programmer edit section *** (Сотрудник.ИНН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.ИНН Set start)

                // *** End programmer edit section *** (Сотрудник.ИНН Set start)
                this.fИНН = value;
                // *** Start programmer edit section *** (Сотрудник.ИНН Set end)

                // *** End programmer edit section *** (Сотрудник.ИНН Set end)
            }
        }
        
        /// <summary>
        /// Номер_телефона.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Номер_телефона CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Номер_телефона CustomAttributes)
        public virtual int Номер_телефона
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Номер_телефона Get start)

                // *** End programmer edit section *** (Сотрудник.Номер_телефона Get start)
                int result = this.fНомер_телефона;
                // *** Start programmer edit section *** (Сотрудник.Номер_телефона Get end)

                // *** End programmer edit section *** (Сотрудник.Номер_телефона Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Номер_телефона Set start)

                // *** End programmer edit section *** (Сотрудник.Номер_телефона Set start)
                this.fНомер_телефона = value;
                // *** Start programmer edit section *** (Сотрудник.Номер_телефона Set end)

                // *** End programmer edit section *** (Сотрудник.Номер_телефона Set end)
            }
        }
        
        /// <summary>
        /// Снилс.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Снилс CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Снилс CustomAttributes)
        public virtual int Снилс
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Снилс Get start)

                // *** End programmer edit section *** (Сотрудник.Снилс Get start)
                int result = this.fСнилс;
                // *** Start programmer edit section *** (Сотрудник.Снилс Get end)

                // *** End programmer edit section *** (Сотрудник.Снилс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Снилс Set start)

                // *** End programmer edit section *** (Сотрудник.Снилс Set start)
                this.fСнилс = value;
                // *** Start programmer edit section *** (Сотрудник.Снилс Set end)

                // *** End programmer edit section *** (Сотрудник.Снилс Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.ФИО CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.ФИО Get start)

                // *** End programmer edit section *** (Сотрудник.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Сотрудник.ФИО Get end)

                // *** End programmer edit section *** (Сотрудник.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.ФИО Set start)

                // *** End programmer edit section *** (Сотрудник.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Сотрудник.ФИО Set end)

                // *** End programmer edit section *** (Сотрудник.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Сотрудник.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Должности CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.New.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Должности Get start)

                // *** End programmer edit section *** (Сотрудник.Должности Get start)
                IIS.New.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (Сотрудник.Должности Get end)

                // *** End programmer edit section *** (Сотрудник.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Должности Set start)

                // *** End programmer edit section *** (Сотрудник.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (Сотрудник.Должности Set end)

                // *** End programmer edit section *** (Сотрудник.Должности Set end)
            }
        }
        
        /// <summary>
        /// Сотрудник.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Подразделения CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Подразделения CustomAttributes)
        [PropertyStorage(new string[] {
                "Подразделения"})]
        [NotNull()]
        public virtual IIS.New.Подразделения Подразделения
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Подразделения Get start)

                // *** End programmer edit section *** (Сотрудник.Подразделения Get start)
                IIS.New.Подразделения result = this.fПодразделения;
                // *** Start programmer edit section *** (Сотрудник.Подразделения Get end)

                // *** End programmer edit section *** (Сотрудник.Подразделения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Подразделения Set start)

                // *** End programmer edit section *** (Сотрудник.Подразделения Set start)
                this.fПодразделения = value;
                // *** Start programmer edit section *** (Сотрудник.Подразделения Set end)

                // *** End programmer edit section *** (Сотрудник.Подразделения Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникE", typeof(IIS.New.Сотрудник));
                }
            }
            
            /// <summary>
            /// "СотрудникL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникL", typeof(IIS.New.Сотрудник));
                }
            }
        }
    }
}
